/**
 * Global skill installation (design §2.1, decision 2).
 *
 * Installs the methodology ONCE, globally, into the selected runtime targets.
 * Claude has its own target; GitHub Copilot and Codex share ~/.agents/skills.
 * Core only by default; add-ons require explicit opt-in (`--addon <name>`,
 * AC-14). Writes only under the given target dirs — never any consumer-repo
 * files (AC-02).
 *
 * Sources (in the published package):
 *   skills/<name>/SKILL.md                 → core (generated by src/generator/sync.js
 *                                             from skills/<name>/canonical.md)
 *   addons/<addon>/<name>/SKILL.md         → opt-in add-ons
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildManifest, writeManifest } from './manifest.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const PACKAGE_ROOT = path.resolve(__dirname, '..', '..');

export function readPackageVersion(root = PACKAGE_ROOT) {
  return JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;
}

/** Skill dirs directly under `dir` that contain a SKILL.md. */
export function listSkills(dir) {
  if (!fs.existsSync(dir)) return [];
  const skills = [];
  for (const name of fs.readdirSync(dir)) {
    const skillDir = path.join(dir, name);
    let stat;
    try {
      stat = fs.statSync(skillDir);
    } catch (err) {
      if (err && err.code === 'ENOENT') continue;
      throw err;
    }
    if (stat.isDirectory() && fs.existsSync(path.join(skillDir, 'SKILL.md'))) {
      skills.push({ name, dir: skillDir });
    }
  }
  return skills;
}

export function listAddonSkills(addonsDir, addon) {
  return listSkills(path.join(addonsDir, addon)).map((s) => ({ ...s, addon }));
}

// Only these install-facing files travel to the global targets — never
// `canonical.md` (the authoring source) or generator scratch files.
const INSTALLABLE_FILES = new Set(['SKILL.md']);

/**
 * Installs the installable files of one skill into `dest`, either by copy or
 * by per-file symlink to `src` (mode: 'link'). In link mode `dest` is still a
 * real directory — only the files are linked — so `canonical.md` never
 * appears in the target and directory-level discovery is unaffected.
 * Returns the list of installed files, for the manifest.
 */
function installSkillArtifacts(src, dest, mode) {
  fs.mkdirSync(dest, { recursive: true });
  const files = [];
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (!entry.isFile() || !INSTALLABLE_FILES.has(entry.name)) continue;
    const srcFile = path.join(src, entry.name);
    const destFile = path.join(dest, entry.name);
    if (mode === 'link') {
      if (fs.existsSync(destFile) || fs.lstatSync(destFile, { throwIfNoEntry: false })) {
        fs.rmSync(destFile, { force: true });
      }
      fs.symlinkSync(srcFile, destFile);
    } else {
      fs.copyFileSync(srcFile, destFile);
    }
    files.push({ name: entry.name, sourcePath: srcFile });
  }
  return files;
}

/**
 * Install core (+ requested add-ons) into each target dir and stamp the version.
 * Returns a summary; writes nothing outside the target dirs.
 *
 * Requires `playbook sync` to have generated SKILL.md next to each
 * canonical.md first — installSkills only ever installs SKILL.md, never the
 * canonical.md source, so a stale/missing SKILL.md installs a stale/missing skill.
 *
 * `mode: 'copy'` (default) is byte-for-byte identical to the pre-manifest
 * behavior. `mode: 'link'` symlinks each installable file to `sourceRoot`
 * instead — dev-only, opt-in via `playbook install --link`.
 */
export function installSkills({ targets, version, addons = [], sourceRoot = PACKAGE_ROOT, mode = 'copy' }) {
  const core = listSkills(path.join(sourceRoot, 'skills'));
  const addonSkills = addons.flatMap((a) => listAddonSkills(path.join(sourceRoot, 'addons'), a));
  const all = [...core, ...addonSkills];

  const installedInto = {};
  for (const [runtime, targetDir] of Object.entries(targets)) {
    fs.mkdirSync(targetDir, { recursive: true });
    const skillFiles = all.map((s) => ({
      name: s.name,
      files: installSkillArtifacts(s.dir, path.join(targetDir, s.name), mode),
    }));
    fs.writeFileSync(path.join(targetDir, '.playbook-version'), `${version}\n`, 'utf8');
    writeManifest(targetDir, buildManifest({ version, mode, sourceRoot, skills: skillFiles }));
    installedInto[runtime] = targetDir;
  }

  return {
    version,
    mode,
    core: core.map((s) => s.name),
    addons: addonSkills.map((s) => `${s.addon}/${s.name}`),
    targets: installedInto,
  };
}
